### ISSUE TITLE
Some Emails Have edX Styles

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitx-theme#130]
Email templates are very confusing in edX platform. Some of them are overridden in the theme, and some are overidden in the database. 

We've identified a number of emails that are using the wrong template. We need to figure out how they can be overridden, and then implement the override. 

If the template can be overidden in the database, you can test it out on the QA server at https://mitx-qa-next.mitx.mit.edu/admin/bulk_email/courseemailtemplate/ and then we can coordinate on moving it into production. 

> The emails sent from the [Membership tab on the Instructor Dash](https://mitx-qa-next.mitx.mit.edu/courses/course-v1:MITx+mkd.upgradeF2020+2020_Fall/instructor#view-membership) have the edX styling. These include enrolled, unenrolled, added as a beta tester, removed from beta testing. They look like this: 
> <img width="1518" alt="enrollment email" src="https://github.mit.edu/storage/user/9183/files/daef7600-a465-11ea-80d4-e34172e3a39f">
>
> The emails sent from [the Email tab in the Instructor Dashboard](https://mitx-qa-next.mitx.mit.edu/courses/course-v1:MITx+mkd.upgrade+2020_Fall/instructor#view-send_email) have the preferred styling and look like this: 
>
> <img width="1518" alt="correct email styling" src="https://github.mit.edu/storage/user/9183/files/33267800-a466-11ea-84c5-694e1f32ef07">

**Comment by pdpinch** [comment]
@briangrossman there is a very old, but low priority issue in xPRO to do similar changes there.

**Comment by pdpinch** [comment]
I had a theory that theses templates were managed in the database, but there's a thread on discuss.openedx.org that suggests that these might be overridden in the theme:

https://discuss.openedx.org/t/how-to-modify-a-email-template/211

**Comment by HamzaIbnFarooq** [comment]
In edX, the emails sent from the `Membership tab` on the `Instructor Dashboard` use `edx_ace` and each email has a different template that `needs to be overridden in theme` in case of any required change.

While the emails sent from `Email tab` are sent using `database bulk email templates` set via the admin panel. These emails seem to be the only ones sent using bulk email templates (at first glance).

The list of emails that use `edx_ace` seems to be the following:
- Account Recovery
- Email Change
- Password Reset
- Response Notification
- Enrollment & Unenrollment by Instructor
- Deletion Notification Message
- Course Update
- Upgrade Reminder

@pdpinch kindly let me know which email templates you want to get changed and in what way?

**Comment by pdpinch** [comment]
Thank you for that research. It's so confusing to have these templates set in difference places! 

For Residential MITx, we need to be sure that the following templates have the correct logo, URLs and address:

- Enrollment & Unenrollment by Instructor
- Course Update
- Response Notification

The following emails should never be sent by Residential MITx, so I don't think we care much what they look like:

- Account Recovery (not used due to Touchstone SAML SSO)
- Email Change  (not used due to Touchstone SAML SSO)
- Password Reset  (not used due to Touchstone SAML SSO)
- Deletion Notification Message (in a campus context, we don't delete student accounts)
- Upgrade Reminder (all courses are "honor" mode) 

cc @briangrossman

**Comment by pdpinch** [comment]
I should double-check this list with the MITx team, but I'm very confident it is correct.

**Comment by HamzaIbnFarooq** [comment]
@pdpinch So we just want to change the logo? and kindly let me know which branch it requires to be merged in?

We need a contact mailing address here as well, just like mitxpro-theme, kidly provide that as well.

**Comment by pdpinch** [comment]
I assume it’s the koa branch again, but @shaidar can confirm. 

Let’s use the same mailing address as xPRO,

> MIT Open Learning, 600 Technology Square, 2nd Floor, Cambridge, MA 02139

**Comment by HamzaIbnFarooq** [comment]
Closed by https://github.com/mitodl/mitx-theme/pull/131
