### ISSUE TITLE
Ginkgo: Hide sign-up button in Studio

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitx-theme#21]
![studio sign up](https://user-images.githubusercontent.com/430126/33431412-418086b0-d5a2-11e7-996d-67ba2b927f8d.png)

**Comment by amir-qayyum-khan** [comment]
@mitodl/devops and @blarghmatey are you guys done with https://github.com/mitodl/edx-platform/pull/56#issuecomment-351751254? if yes then please close it
