### ISSUE TITLE
Typo in Terms of Service 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitx-theme#28]
from https://odl.zendesk.com/agent/tickets/11060

> On the new Residential terms of service page (in the site footer)this sentence:
> "If you encounter any issues with MITx Residential MITx, please contact…”
> needs to be changed to:
> "If you encounter any issues with Residential MITx, please contact…"

**Comment by pdpinch** [comment]
Amir, this repo is a little more complex now, because we have a separate branches for our staging server and for our production server. After you've done this, you should open a PR against the `ficus` branch *and* the `ficus-draft` branch. 

unless @blarghmatey tells us to do something different.

**Comment by amir-qayyum-khan** [comment]
ok

**Comment by blarghmatey** [comment]
At the moment there isn't actually a difference in the theme between the two branches, so you can issue the PR against the ficus branch and I can cherry-pick it into the other branch.
