### ISSUE TITLE
Ginkgo: don't allow help button to wrap when username is long

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitx-theme#40]
See https://github.mit.edu/mitx/Spring-2018/issues/26

<image src="https://github.mit.edu/storage/user/9183/files/92661240-de7e-11e7-9829-99ba04891e45">

**Comment by pdpinch** [comment]
If appropriate, this could be an upstream fix to edX, instead of a theme fix.

**Comment by annagav** [comment]
It was fixed upstream by using a new template header/user_dropdown.html) see comment https://github.com/edx/edx-platform/blob/160dba9505eb98949a93c035ffbf676f3ac6bbd4/lms/templates/navigation/navigation.html#L5
