### ISSUE TITLE
Change the enroll_email_allowedmessage

### ISSUE THREAD

**Issue by NotoriousMKD** [mitodl/mitx-theme#57]
The current enrollment email for users who have been enrolled in a course but haven't registered yet for MITx needs to include instructions that will get the user enrolled in the course. Currently, auto-enrollment for unregistered users isn't working properly, so we need to add some more details to [this email template](https://github.com/mitodl/mitx-theme/blob/master/lms/templates/emails/enroll_email_allowedmessage.txt).

Here's a draft of what the updated email could say: 

> Dear student,
>
>You have been invited to join [Course Name] at [Course URL] by a member of the course staff.
>
>To access the course, you will first need to register for MITx at lms.mitx.mit.edu with your Kerberos ID or Touchstone account. If you do not have a Kerberos ID and need to set up a Touchstone account, please contact your instructor for detailed directions.
>
>Once you have registered and logged in, visit the course site at [Course URL] to complete your enrollment.
>
>Email mitx-support@mit.edu if you have any problems with your enrollment.

**Comment by pdpinch** [comment]
Can you paste in here a sample of the current email?

**Comment by NotoriousMKD** [comment]
Dear student,

You have been invited to join ENGINEERING DEMOCRATIC DEVELOPMENT IN CONTEMPORARY AFRICA at lms.mitx.mit.edu by a member of the course staff.

To finish your registration, please visit lms.mitx.mit.edu/dashboard
You will need to login with Touchstone to access this page. If you do not have a Touchstone account, please contact your instructor for detailed directions.
Once you have logged in with Touchstone, you will see ENGINEERING DEMOCRATIC DEVELOPMENT IN CONTEMPORARY AFRICA listed on your dashboard.

----
This email was automatically sent from lms.mitx.mit.edu to mkdmittest@gmail.com
