### ISSUE TITLE
Hawthorn: user drop down menu doesn't work on dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitx-theme#69]
I think this is a Theme issue, but I'm not sure. 

See https://github.mit.edu/mitx/Summer-2018/issues/2

**Comment by pdpinch** [comment]
@amir-qayyum-khan is there a PR for this?

**Comment by amir-qayyum-khan** [comment]
course page is rendered by a fragment. you can find view here openedx/features/course_experience/views/course_home.py. This fragment is unable to load css like rest of pages. I am trying to look into case

**Comment by amir-qayyum-khan** [comment]
@pdpinch i am able to fix issue here https://github.com/mitodl/mitx-theme/pull/73

**Comment by pdpinch** [comment]
@amir-qayyum-khan can you tell if you code was deployed to https://mitx-qa-next.mitx.mit.edu/dashboard -- it doesn't seem to be working for me.

**Comment by amir-qayyum-khan** [comment]
@pdpinch it is working
https://mitx-qa-next.mitx.mit.edu/courses/course-v1:MITx+2.001r_7+2018_Spring/course/

<img width="666" alt="screen shot 2018-05-22 at 5 43 06 pm" src="https://user-images.githubusercontent.com/10431250/40363000-9f332c7c-5de7-11e8-89b9-861328dc7018.png">

**Comment by amir-qayyum-khan** [comment]
Drop down on dashboard is not working

**Comment by amir-qayyum-khan** [comment]
it is working on devstack. My be theme compilation issue @mitodl/devops ?

<img width="1259" alt="screen shot 2018-05-22 at 7 26 44 pm" src="https://user-images.githubusercontent.com/10431250/40368850-169c92cc-5df6-11e8-8b56-019c6ca215c5.png">

**Comment by pdpinch** [comment]
This is working now at https://mitx-qa-next.mitx.mit.edu/dashboard -- I think the earlier problem was due to a failed deployment.
