### ISSUE TITLE
Hawthorn: TemplateDoesNotExist: head-extra.html

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitx-theme#71]
The following error is causing a 500 error when viewing /dashboard

```
018-05-15 15:14:46,218 WARNING 27630 [django.template] loader_tags.py:232 - Exception raised while rendering {% include %} for template 'unknown'. Empty string rendered instead.
    Traceback (most recent call last):
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 204, in render
        template = context.template.engine.get_template(template_name)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/engine.py", line 162, in get_template
        template, origin = self.find_template(template_name)
      File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/engine.py", line 148, in find_template
        raise TemplateDoesNotExist(name, tried=tried)
    TemplateDoesNotExist: head-extra.html
```

**Comment by pdpinch** [comment]
@annagav have you started on this? If not @amir-qayyum-khan can you take a look?

**Comment by amir-qayyum-khan** [comment]
@pdpinch are we talking about LMS. Are there steps to reproduce it?

**Comment by amir-qayyum-khan** [comment]
unable to reproduce. @mitodl/devops please provide me trace from logs.

**Comment by amir-qayyum-khan** [comment]
@pdpinch i was not able to reproduce it but i removed that line which looks for template and things are working fine

https://github.com/mitodl/mitx-theme/pull/74

**Comment by pdpinch** [comment]
It look likes this template was removed but it's include was not. 

https://github.com/edx/edx-platform/blame/master/lms/templates/main.html#L120

The include depends on a `is_theming_enabled="True"`. We're not sure why that flag might be getting set on mitx-qa-draft-next but not on mitx-qa-next. 

Amir's theme PR should fix the issue, but it's still a curiosity. I think we should merge the fix for now but I'll open a tech debt issue to look into this further.
