### ISSUE TITLE
font-size mixing error

### ISSUE THREAD

**Issue by jpmateo022** [mitodl/mitx-theme#86]
Hi,

Im currently using your edx theme as my based theme but when I execute

sudo ./edxapp-update-assets-lms 

I got this error:

![image](https://user-images.githubusercontent.com/26633918/41213906-d646b286-6d7a-11e8-9749-1dfc25749773.png)

Currently Using ginkgo.master release (OpenEdx Native)

Hope you can help me.

**Comment by pdpinch** [comment]
For what it's worth, the master branch of this repo is being used with the master branch of edx-platform (in preparation of the the Hawthorn release). 

If you want a known-good theme for ginkgo, you should try the ginkgo branch: https://github.com/mitodl/mitx-theme/tree/ginko

**Comment by jpmateo022** [comment]
Actually, I'm using the ginkgo branch

https://github.com/mitodl/mitx-theme/tree/ginkgo

Correct me if I'm wrong, maybe the theme is not compatible to OpenEdx Native.

This OpenEdx theming is driving me nuts haha.

**Comment by pdpinch** [comment]
@amir-qayyum-khan any idea what might be happening here? As far as I can recall, we didn't see this error using the ginkgo theme branch with ginko deployments.

**Comment by amir-qayyum-khan** [comment]
it tested this on vagrant
*edx:* `open-release/ginkgo.master`
*mitx-theme:* `ginkgo`
*command:*  `paver update_assets`

It worked fine as expect. @jpmateo022  you may have cache issue? can you clean cache. This can happen after switching to different git branches, you can do `git clean -xfd` on both theme and edx repo. Also make you you have right branches set.

**Comment by pdpinch** [comment]
I'm going to close this since we haven't had any follow-up. Feel free to re-open if you can share steps to reproduce.
