### ISSUE TITLE
Ironwood: revert Removed PARTNER_SUPPORT_EMAIL from cms template

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitx-theme#90]
I don't think we need this theme override anymore, as long as we set `PARTNER_SUPPORT_EMAIL` to the Residential MITx support email address. 

We should probably remove sock.html altogether. If that's too drastic we can just revert https://github.com/mitodl/mitx-theme/commit/98109e59bab98e104820e4bef8f1faa519940a22

**Comment by annagav** [comment]
Here is a screenshot without overriding sock.html:
<img width="1378" alt="screen shot 2018-11-21 at 4 33 53 pm" src="https://user-images.githubusercontent.com/7574259/48869535-95031d80-edab-11e8-928c-1f9c1f6a5dd5.png">

**Comment by pdpinch** [comment]
We already have all those links, except for "Open edX Portal"

Let's remove the override for sock.html and call it a day.

**Comment by pdpinch** [comment]
There's not much point in merging this into Hawthorn. We can let it wait until we get to Ironwood.

**Comment by pdpinch** [comment]
I opened a PR that removed sock.html #94 for when we are ready.
