### ISSUE TITLE
revert "New look message on /courses page" #89

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitx-theme#92]
We don't need the message that was added in #89 any more.

**Comment by pdpinch** [comment]
@annagav I assume this is a quick change

**Comment by pdpinch** [comment]
This change can be merged into master of this repo (for the Spring 2019 release)

**Comment by Ayub-Khan** [comment]
@pdpinch I have created the following pr with the changes [Pull Request](https://github.com/mitodl/mitx-theme/pull/93)
