### ISSUE TITLE
Update favicon in studio to match lms

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitx-theme#96]
According to [Lawrence](https://blog.lawrencemcdaniel.com/) we can do this with an override of cms/main/template:

![image](https://user-images.githubusercontent.com/430126/56961357-989c8c80-6b21-11e9-84ec-8220d22a960d.png)

**Comment by annagav** [comment]
This was fixed in this PR https://github.com/edx/edx-platform/pull/20358

I tested it out:
![Screen Shot 2019-07-03 at 3 58 04 PM](https://user-images.githubusercontent.com/7574259/60621452-b4cfda80-9dab-11e9-8ac6-0ff09565f77a.png)

**Comment by pdpinch** [comment]
Finally we can cross this off the list! 

Well, maybe next semester. =)
