### ISSUE TITLE
Revert enrollment email template

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mitx-theme#97]
When an instructor manually enrolls or unenrolls a student from the[ instructor dash,](https://mitx-qa-next.mitx.mit.edu/courses/course-v1:MITx+mkd.201915+2019_Summer/instructor#view-membership) they can choose to send an automated email. 

The current production style of the email looks like this: 
![screenshot 2019-05-20 13 36 34](https://github.mit.edu/storage/user/9183/files/4c7182aa-7b04-11e9-8318-ac5f595af22d)

The QA email looks like this:
![screenshot 2019-05-20 13 35 35](https://github.mit.edu/storage/user/9183/files/2a5cdcaa-7b04-11e9-9de7-317617aa0ff0)

All things being equal, the residential team would prefer the current production template, and not the version generated on the QA server.

**Comment by annagav** [comment]
@pdpinch Just to avoid confusion, could you specify with one is the "old template"?

**Comment by pdpinch** [comment]
The [first one](https://camo.githubusercontent.com/f04f25d56777b8b82a618aa1d966344cedbd9916/68747470733a2f2f6769746875622e6d69742e6564752f73746f726167652f757365722f393138332f66696c65732f34633731383261612d376230342d313165392d383331382d616335663539356166323264) in the description.
